### ISSUE TITLE
Cannot connect to anything in Drill

### ISSUE THREAD

**Issue by hipogeniq** [JohnOmernik/sqlalchemy-drill#83]
Running latest superset and apache drill running locally. I cannot add any connection for drill (not even the dfs ) dummy thing. Test connect works fine. When I do "Connect" it returns:
sqlalchemy.exc.DatabaseError: (sqlalchemy_drill.drilldbapi.api_exceptions.DatabaseError) 'Final Drill query state is FAILED HTTP ERROR: None'
[SQL: SHOW DATABASES]

the queries are running fine in Drill.

**Comment by jnturton** [comment]
You can get more verbose error information by setting `drill.exec.http.rest.errors.verbose` to true or by looking in the Drill log file.

**Comment by hipogeniq** [comment]
10:03:45.122 [1bdc1d30-b348-c7a8-4688-f9eaab53c78e:frag:0:0] ERROR o.a.calcite.jdbc.DynamicRootSchema - Failed to load schema for box
com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .0c4e333b75a695376c44d32b89e1b7b99]
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:95)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:760)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:437)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:404)
        at com.box.sdk.BoxFolder.getInfo(BoxFolder.java:323)
        at org.apache.drill.exec.store.dfs.BoxFileSystem.getFileStatus(BoxFileSystem.java:287)
        at org.apache.hadoop.fs.FileSystem.access(FileSystem.java:2638)
        at org.apache.drill.exec.store.dfs.DrillFileSystem.access(DrillFileSystem.java:751)
        at org.apache.drill.exec.store.dfs.WorkspaceSchemaFactory.accessible(WorkspaceSchemaFactory.java:192)
        at org.apache.drill.exec.store.dfs.WorkspaceSchemaFactory.createSchema(WorkspaceSchemaFactory.java:208)
        at org.apache.drill.exec.store.dfs.FileSystemSchemaFactory$FileSystemSchema.<init>(FileSystemSchemaFactory.java:96)
        at org.apache.drill.exec.store.dfs.FileSystemSchemaFactory.registerSchemas(FileSystemSchemaFactory.java:73)
        at org.apache.drill.exec.store.dfs.FileSystemPlugin.registerSchemas(FileSystemPlugin.java:290)
        at org.apache.calcite.jdbc.DynamicRootSchema.registerSchemasWithRetry(DynamicRootSchema.java:112)
        at org.apache.calcite.jdbc.DynamicRootSchema.loadSchemaFactory(DynamicRootSchema.java:156)
        at org.apache.calcite.jdbc.DynamicRootSchema.getSchema(DynamicRootSchema.java:88)
        at org.apache.calcite.jdbc.DynamicRootSchema.getImplicitSubSchema(DynamicRootSchema.java:74)
        at org.apache.calcite.jdbc.CalciteSchema.getSubSchema(CalciteSchema.java:271)
        at org.apache.calcite.jdbc.CalciteSchema$SchemaPlusImpl.getSubSchema(CalciteSchema.java:690)
        at org.apache.drill.exec.store.ischema.InfoSchemaRecordGenerator.scanSchemaImpl(InfoSchemaRecordGenerator.java:86)
        at org.apache.drill.exec.store.ischema.InfoSchemaRecordGenerator.scanSchema(InfoSchemaRecordGenerator.java:64)
        at org.apache.drill.exec.store.ischema.InfoSchemaRecordGenerator.scanSchema(InfoSchemaRecordGenerator.java:54)
        at org.apache.drill.exec.store.ischema.InfoSchemaTableType.getRecordReader(InfoSchemaTableType.java:88)
        at org.apache.drill.exec.store.ischema.InfoSchemaBatchCreator.getBatch(InfoSchemaBatchCreator.java:35)
        at org.apache.drill.exec.store.ischema.InfoSchemaBatchCreator.getBatch(InfoSchemaBatchCreator.java:30)
        at org.apache.drill.exec.physical.impl.ImplCreator.getRecordBatch(ImplCreator.java:158)
        at org.apache.drill.exec.physical.impl.ImplCreator.getChildren(ImplCreator.java:181)
        at org.apache.drill.exec.physical.impl.ImplCreator.getRecordBatch(ImplCreator.java:139)
        at org.apache.drill.exec.physical.impl.ImplCreator.getChildren(ImplCreator.java:181)
        at org.apache.drill.exec.physical.impl.ImplCreator.getRootExec(ImplCreator.java:115)
        at org.apache.drill.exec.physical.impl.ImplCreator.getExec(ImplCreator.java:90)
        at org.apache.drill.exec.work.fragment.FragmentExecutor.run(FragmentExecutor.java:290)
        at org.apache.drill.common.SelfCleaningRunnable.run(SelfCleaningRunnable.java:38)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by jnturton** [comment]
Excellent, we see what's going wrong now! The `SHOW DATABASES` query being sent by Superset is causing Drill to go through every enabled storage plugin to fetch schema information. You've got an enabled storage plugin named 'box' based on Box cloud storage and that plugin is broken, apparently due to an authorisation problem, causing `SHOW DATABASES` to fail. You can disable it manually and also see the [automatic plugin disablement feature in Drill 1.21](https://drill.apache.org/docs/configuring-storage-plugins/#automatic-retry-and-disable) if you want a measure to deal with this kind of thing in future.

**Comment by hipogeniq** [comment]
Wonderful! Thanks. That did the trick!

**Comment by jnturton** [comment]
I think we can close this issue.

**Comment by jnturton** [comment]
@cgivre we can close this one.
